### ISSUE TITLE
What is the recommended replacement for http_redirect in v2+?

### ISSUE THREAD

**Issue by chrisrichard** [m6w6/ext-http#18]
Also - where is the right place to ask this question?

**Comment by m6w6** [comment]
There's no equivalent of http_redirect() in v2, because 90% of use cases can be satisfied with just header("Location: ...") or https://mdref.m6w6.name/http/Env/setResponseHeader

You can usually find me in #php.pecl on EFNET or [![Join the chat at https://gitter.im/m6w6/ext-http](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/m6w6/ext-http?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
