### ISSUE TITLE
setOptions() with empty string as value

### ISSUE THREAD

**Issue by rcanavan** [m6w6/ext-http#33]
I've stumbled accross a problem related to #32 when attempting to override http_proxy and related environment variables by setting CURLOPT_PROXY to an empty string via 'proxyhost'. ext-http internally substitutes NULL for the empty string, which does not have the desired effect. The enclosed trivial patch retains the empty string as is when calling curl_easy_setopt().

[setopt_empty_string.patch.txt](https://github.com/m6w6/ext-http/files/193522/setopt_empty_string.patch.txt)

**Comment by m6w6** [comment]
Thank you for the report! Unfortunately, I think this is not the correct fix for that problem, because it will prevent from all other options receiving NULL, which might beed it. If an empty string is valid for a particular option, we should remove the `PHP_HTTP_CURLE_OPTION_CHECK_STRLEN` flag from that option.

**Comment by rcanavan** [comment]
Removing the PHP_HTTP_CURLE_OPTION_CHECK_STRLEN flag from the proxyhost option works just as well for me.

[setopt_empty_string.patch.txt](https://github.com/m6w6/ext-http/files/195145/setopt_empty_string.patch.txt)
[setopt_empty_string.patch.txt](https://github.com/m6w6/ext-http/files/195148/setopt_empty_string.patch.txt)

**Comment by m6w6** [comment]
Great, thanks for verifying. I'm currently checking the curl sources to see if any more settings are affected by this.
